
name: spacexApp-CI

on: [push]


jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploying graphql powered app to netlify
    steps:
      - uses: actions/checkout@v2

      - name: Install Nodejs
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12
          
      - name: Deploy to Netlify
        uses: jsmrcaga/action-netlify-deploy@v1.1.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_DEPLOY_TO_PROD: true
